version: 2
jobs:
  build:
    docker:
    - image: cimg/python:3.10.6
      auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - restore_cache:
          keys: 
           - v1-dependancies-{{ .circleci }}-{{ checksum "/.circleci/requirements.txt"}}
           - v1-dependencies-
      - save_cache:
          paths:
          - ./venv
          key: v1-{{ .circleci }}-{{ checksum "/.circleci/requirements.txt" }
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r .circleci/requirements.txt
      - run:
          command: |
            . venv/bin/activate
            python script_to_db.py test