version: 2
jobs:
  build:
    docker:
    - image: cimg/python:3.10.6
      auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .circleci }}-{{ checksum "data-ingestion-script/requirements.txt"}}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .circleci }}-{{ checksum "data-ingestion-script/requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python script_to_db.py test