version: 2
jobs:
  build:
    docker:
    - image: cimg/python:3.10.6
      auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - restore_cache:
          keys: 
           - v1-dependancies--{{ checksum "requirements.txt"}}
           - v1-dependencies-
      - save_cache:
          paths:
          - ./venv
          key: v1--{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            python script_to_db.py test